# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  categories:
    - Care
    - Education
    - Emergency
    - Food
    - Goods
    - Health
    - Housing
    - Legal
    - Money
    - Transit
    - Work

development:
  <<: *default
  secret_key_base: 208ee9fe46ab8d0019af19c0216aabb582c5874f420a8d87bf59310b8726ba6b1f020bd539ca300e63a34981d32cb57a03c1e15cf7900306298f2ffedf6fd2ca

test:
  <<: *default
  secret_key_base: e756cc6049e50ec69d62a8c484ef01e740f5818e67d6565985381f8bf8b016cb8b0d7fa4e569fcf501e60fb4f5592ce0d602c2cbb11b99dca0f5eef4a7f933d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
